version: '3'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  nodejs:
    build: ./gate-simulator
    ports:
      - "9999:9999"
    install:
    # запускаем SUT (запоминаем информацию о процессе в переменной $App)
      - ps: $App = Start-Process -FilePath javaScript -ArgumentList "-js ./gate-simulator/app.js" -PassThru
    build_script:
      - ps: ./npm start --info "_properties = initProperties("./Properties.properties")"
    on_finish:
      - ps: Stop-Process -Id $App.Id  # оставливаем SUT